{% set version = "2.106.1" %}

package:
  name: dtools
  version: {{ version }}

source:
  url: https://github.com/dlang/tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7c85679167fc9166c9cedf2e14e887279bb49c20f5dc4f299b2ee0eb40932440

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
  run:
    - ldc

test:
  commands:
    - rdmd --version 2>&1 | grep -q Usage
  requires:
    - m2-grep  # [win]

about:
  home: https://github.com/dlang/tools/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Ancillary tools for the D programming language compiler

extra:
  recipe-maintainers:
    - dpryan79
