{% set version = "2.104.1" %}

package:
  name: dtools
  version: {{ version }}

source:
  url: https://github.com/dlang/tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3013074eb6770ecb0ee33869f2215a8b84be4b07a8b5c39baa673ca716011210

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - ldc
  run:
    - ldc

test:
  commands:
    - rdmd --version 2>&1 | grep -q Usage
  requires:
    - m2-grep  # [win]

about:
  home: https://github.com/dlang/tools/
  license: BSL-1.0
  license_file: LICENSE.txt
  summary: Ancillary tools for the D programming language compiler

extra:
  recipe-maintainers:
    - dpryan79
